services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - sabd_net

networks:
  sabd_net:
    external: true


volumes:
  grafana_storage: